#!/bin/zsh

folder="/home/oc/Notes"

newnote () {
    name="$(echo "" | rofi -dmenu -p "Enter a name:")"
    [[ -z "$name" ]] && return
    setsid -w -f foot --hold -e nvim "$folder/$name"
}

selected () {
    local files choice
    files=("${(@f)$(ls -1t "$folder" 2>/dev/null)}")
    files=("New" "${files[@]}")
    choice=$(printf "%s\n" "${files[@]}" | rofi -dmenu -i -p "Choose note or create new:")
    
    case "$choice" in
        "New") newnote ;;
        "") exit ;;  # Nothing selected
        *)     setsid -w -f foot --hold -e nvim "$folder/$choice"
 ;;
    esac
}

selected

