#!/bin/sh

while true; do
		# Wait for Waybar to exist
		while ! pgrep -x "waybar" >/dev/null; do
				sleep 0.5
		done

		playerctl -a metadata --format '{{status}} - {{artist}} - {{title}}' --follow | while read -r line; do
		pgrep -x "waybar" >/dev/null && pkill -RTMIN+10 waybar
done
done
