#!/bin/sh

# This loop updates the mpd statusbar module whenever a media player changes state.
# Requires playerctl and a MPRIS-compatible media player.

while : ; do
    playerctl -F metadata >/dev/null && kill -45 "$(pidof "${STATUSBAR:-dwmblocks}")" || break
done

