#!/bin/env bash
if pgrep -x "wf-recorder" > /dev/null; then
    pkill -INT -x wf-recorder
    notify-send -h string:wf-recorder:record -t 1000 "Finished Recording"
    exit 0
fi

notify-send -h string:wf-recorder:record -t 1000 "Recording Started"
dateTime=$(date +%m-%d-%Y-%H:%M:%S)
wf-recorder --audio=alsa_output.pci-0000_00_1f.3.analog-stereo.monitor --bframes max_b_frames -f "$HOME/videos/$dateTime.mkv"
